import { Permission } from '@prisma/client';

import { mergeTableData } from './generate-merge-data.script';
import { PermissionCodes } from '../../../libs/common/src/constants/permission-codes.constants';

export const permissionPostDeployAsync = async () => {
  const sourceData: Permission[] = [
    { id: 1, name: PermissionCodes.RegistrationRequest.READ },
    { id: 2, name: PermissionCodes.RegistrationRequest.CREATE },
    { id: 3, name: PermissionCodes.RegistrationRequest.UPDATE },
    { id: 4, name: PermissionCodes.RegistrationRequest.DELETE },
    { id: 5, name: PermissionCodes.Product.READ },
    { id: 6, name: PermissionCodes.Product.CREATE },
    { id: 7, name: PermissionCodes.Product.UPDATE },
    { id: 8, name: PermissionCodes.Product.DELETE },
    { id: 9, name: PermissionCodes.ProductCategory.READ },
    { id: 10, name: PermissionCodes.ProductCategory.CREATE },
    { id: 11, name: PermissionCodes.ProductCategory.UPDATE },
    { id: 12, name: PermissionCodes.ProductCategory.DELETE },
    { id: 13, name: PermissionCodes.Supplier.READ },
    { id: 14, name: PermissionCodes.Supplier.CREATE },
    { id: 15, name: PermissionCodes.Supplier.UPDATE },
    { id: 16, name: PermissionCodes.Supplier.DELETE },
    { id: 17, name: PermissionCodes.Vehicle.READ },
    { id: 18, name: PermissionCodes.Vehicle.CREATE },
    { id: 19, name: PermissionCodes.Vehicle.UPDATE },
    { id: 20, name: PermissionCodes.Vehicle.DELETE },
    { id: 21, name: PermissionCodes.Repair.READ },
    { id: 22, name: PermissionCodes.Repair.CREATE },
    { id: 23, name: PermissionCodes.Repair.UPDATE },
    { id: 24, name: PermissionCodes.Repair.DELETE },
    { id: 25, name: PermissionCodes.PurchaseOrder.READ },
    { id: 26, name: PermissionCodes.PurchaseOrder.CREATE },
    { id: 27, name: PermissionCodes.PurchaseOrder.UPDATE },
    { id: 28, name: PermissionCodes.PurchaseOrder.DELETE },
    { id: 29, name: PermissionCodes.Cart.READ },
    { id: 30, name: PermissionCodes.Cart.CREATE },
    { id: 31, name: PermissionCodes.Cart.UPDATE },
    { id: 32, name: PermissionCodes.Cart.DELETE },
    { id: 33, name: PermissionCodes.MaintenancePlanItem.READ },
    { id: 34, name: PermissionCodes.MaintenancePlanItem.CREATE },
    { id: 35, name: PermissionCodes.MaintenancePlanItem.UPDATE },
    { id: 36, name: PermissionCodes.MaintenancePlanItem.DELETE },
    { id: 37, name: PermissionCodes.Maintenance.READ },
    { id: 38, name: PermissionCodes.Maintenance.CREATE },
    { id: 39, name: PermissionCodes.Maintenance.UPDATE },
    { id: 40, name: PermissionCodes.Maintenance.DELETE },
    { id: 41, name: PermissionCodes.Stock.READ },
    { id: 42, name: PermissionCodes.Stock.CREATE },
    { id: 43, name: PermissionCodes.Stock.UPDATE },
    { id: 44, name: PermissionCodes.Stock.DELETE },
    { id: 45, name: PermissionCodes.StockChange.READ },
    { id: 46, name: PermissionCodes.StockChange.CREATE },
    { id: 47, name: PermissionCodes.StockChange.UPDATE },
    { id: 48, name: PermissionCodes.StockChange.DELETE },
    { id: 49, name: PermissionCodes.MaintenanceItem.READ },
    { id: 50, name: PermissionCodes.MaintenanceItem.CREATE },
    { id: 51, name: PermissionCodes.MaintenanceItem.UPDATE },
    { id: 52, name: PermissionCodes.MaintenanceItem.DELETE },
    { id: 53, name: PermissionCodes.ServiceSupplier.READ },
    { id: 54, name: PermissionCodes.ServiceSupplier.CREATE },
    { id: 55, name: PermissionCodes.ServiceSupplier.UPDATE },
    { id: 56, name: PermissionCodes.ServiceSupplier.DELETE },
    { id: 57, name: PermissionCodes.Order.READ },
    { id: 58, name: PermissionCodes.Order.CREATE },
    { id: 59, name: PermissionCodes.Order.UPDATE },
    { id: 60, name: PermissionCodes.Order.DELETE },
    { id: 61, name: PermissionCodes.Shipment.READ },
    { id: 62, name: PermissionCodes.Shipment.CREATE },
    { id: 63, name: PermissionCodes.Shipment.UPDATE },
    { id: 64, name: PermissionCodes.Shipment.DELETE },
    { id: 65, name: PermissionCodes.Notification.READ },
    { id: 66, name: PermissionCodes.Notification.CREATE },
    { id: 67, name: PermissionCodes.Notification.UPDATE },
    { id: 68, name: PermissionCodes.Notification.DELETE },
  ];

  await mergeTableData('Permission', sourceData);
};
