export const PermissionCodes = {
  RegistrationRequest: {
    READ: 'registration-request:read',
    CREATE: 'registration-request:create',
    UPDATE: 'registration-request:update',
    DELETE: 'registration-request:delete',
  },
  Product: {
    READ: 'product:read',
    CREATE: 'product:create',
    UPDATE: 'product:update',
    DELETE: 'product:delete',
  },
  ProductCategory: {
    READ: 'product-category:read',
    CREATE: 'product-category:create',
    UPDATE: 'product-category:update',
    DELETE: 'product-category:delete',
  },
  Supplier: {
    READ: 'supplier:read',
    CREATE: 'supplier:create',
    UPDATE: 'supplier:update',
    DELETE: 'supplier:delete',
  },
  Vehicle: {
    READ: 'vehicle:read',
    CREATE: 'vehicle:create',
    UPDATE: 'vehicle:update',
    DELETE: 'vehicle:delete',
  },
  Repair: {
    READ: 'repair:read',
    CREATE: 'repair:create',
    UPDATE: 'repair:update',
    DELETE: 'repair:delete',
  },
  PurchaseOrder: {
    READ: 'purchase-order:read',
    CREATE: 'purchase-order:create',
    UPDATE: 'purchase-order:update',
    DELETE: 'purchase-order:delete',
  },
  Cart: {
    READ: 'cart:read',
    CREATE: 'cart:create',
    UPDATE: 'cart:update',
    DELETE: 'cart:delete',
  },
  MaintenancePlanItem: {
    READ: 'maintenance-plan-item:read',
    CREATE: 'maintenance-plan-item:create',
    UPDATE: 'maintenance-plan-item:update',
    DELETE: 'maintenance-plan-item:delete',
  },
  Maintenance: {
    READ: 'maintenance:read',
    CREATE: 'maintenance:create',
    UPDATE: 'maintenance:update',
    DELETE: 'maintenance:delete',
  },
  StockChange: {
    READ: 'stock-change:read',
    CREATE: 'stock-change:create',
    UPDATE: 'stock-change:update',
    DELETE: 'stock-change:delete',
  },
  Stock: {
    READ: 'stock:read',
    CREATE: 'stock:create',
    UPDATE: 'stock:update',
    DELETE: 'stock:delete',
  },
  MaintenanceItem: {
    READ: 'maintenance-item:read',
    CREATE: 'maintenance-item:create',
    UPDATE: 'maintenance-item:update',
    DELETE: 'maintenance-item:delete',
  },
  ServiceSupplier: {
    READ: 'service-supplier:read',
    CREATE: 'service-supplier:create',
    UPDATE: 'service-supplier:update',
    DELETE: 'service-supplier:delete',
  },
  Order: {
    READ: 'order:read',
    CREATE: 'order:create',
    UPDATE: 'order:update',
    DELETE: 'order:delete',
  },
  Shipment: {
    READ: 'shipment:read',
    CREATE: 'shipment:create',
    UPDATE: 'shipment:update',
    DELETE: 'shipment:delete',
  },
};
