import { Module } from '@nestjs/common';

import { RedisServiceModule } from '@mp/common/services';

import {
  UserRepository,
  PrismaService,
  RegistrationRequestRepository,
  RegistrationRequestStatusRepository,
  TownRepository,
  ProductRepository,
  PrismaUnitOfWork,
  ClientRepository,
  ProductCategoryRepository,
  SupplierRepository,
  StockRepository,
  AddressRepository,
  VehicleRepository,
  RepairRepository,
  ServiceSupplierRepository,
  StockChangeRepository,
  MaintenanceItemRepository,
  MaintenancePlanItemRepository,
  MaintenanceRepository,
  OrderRepository,
  OrderItemRepository,
  PaymentDetailRepository,
  ShipmentRepository,
  BillItemRepository,
  BillRepository,
} from './services';
import { PurchaseOrderRepository } from './services/purchase-order/purchase-order.repository';
import { PurchaseOrderItemRepository } from './services/purchase-order-item/purchase-order-item.repository';
@Module({
  imports: [RedisServiceModule],
  providers: [
    PrismaService,
    UserRepository,
    RegistrationRequestRepository,
    RegistrationRequestStatusRepository,
    TownRepository,
    ProductRepository,
    ProductCategoryRepository,
    PrismaUnitOfWork,
    ClientRepository,
    ProductCategoryRepository,
    SupplierRepository,
    StockRepository,
    AddressRepository,
    TownRepository,
    VehicleRepository,
    RepairRepository,
    ServiceSupplierRepository,
    PurchaseOrderRepository,
    PurchaseOrderItemRepository,
    StockChangeRepository,
    MaintenanceItemRepository,
    MaintenancePlanItemRepository,
    MaintenanceRepository,
    OrderRepository,
    OrderItemRepository,
    PaymentDetailRepository,
    ShipmentRepository,
    BillRepository,
    BillItemRepository,
  ],
  exports: [
    UserRepository,
    RegistrationRequestRepository,
    RegistrationRequestStatusRepository,
    TownRepository,
    ProductRepository,
    ProductCategoryRepository,
    PrismaUnitOfWork,
    ClientRepository,
    ProductCategoryRepository,
    SupplierRepository,
    StockRepository,
    AddressRepository,
    TownRepository,
    VehicleRepository,
    RepairRepository,
    ServiceSupplierRepository,
    PurchaseOrderRepository,
    PurchaseOrderItemRepository,
    StockChangeRepository,
    MaintenanceItemRepository,
    MaintenancePlanItemRepository,
    MaintenanceRepository,
    OrderRepository,
    OrderItemRepository,
    PaymentDetailRepository,
    ShipmentRepository,
    BillRepository,
    BillItemRepository,
    PrismaService,
  ],
})
export class RepositoryModule {}
