import { Module } from '@nestjs/common';

import {
  UserRepository,
  PrismaService,
  RegistrationRequestRepository,
  RegistrationRequestStatusRepository,
  TownRepository,
  ProductRepository,
  PrismaUnitOfWork,
  ClientRepository,
  ProductCategoryRepository,
  SupplierRepository,
  StockRepository,
  AddressRepository,
  VehicleRepository,
  RepairRepository,
} from './services';
@Module({
  providers: [
    PrismaService,
    UserRepository,
    RegistrationRequestRepository,
    RegistrationRequestStatusRepository,
    TownRepository,
    ProductRepository,
    ProductCategoryRepository,
    PrismaUnitOfWork,
    ClientRepository,
    ProductCategoryRepository,
    SupplierRepository,
    StockRepository,
    AddressRepository,
    TownRepository,
    VehicleRepository,
    RepairRepository,
  ],
  exports: [
    UserRepository,
    RegistrationRequestRepository,
    RegistrationRequestStatusRepository,
    TownRepository,
    ProductRepository,
    ProductCategoryRepository,
    PrismaUnitOfWork,
    ClientRepository,
    ProductCategoryRepository,
    SupplierRepository,
    StockRepository,
    AddressRepository,
    TownRepository,
    VehicleRepository,
    RepairRepository,
  ],
})
export class RepositoryModule {}
