
name: Vercel Development Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
jobs:
  Deploy-Development:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: Pull Vercel Environment Variables
        run: vercel env pull .env --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: Build Project Artifacts
        run: |
          OUTPUT_DIR=$(vercel build --token=${{ secrets.VERCEL_TOKEN }} | grep -oP "Output Directory: \K.*")
          echo "Detected Output Directory: $OUTPUT_DIR"
          echo "OUTPUT_DIR=$OUTPUT_DIR" >> $GITHUB_ENV
      
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}